### ISSUE TITLE
Please add wiring diagram

### ISSUE THREAD

**Issue by manuelrwong** [PotatoNukeMk1/IBUSTelemetryAdapter#1]
Looking to build this, can you please include a wiring diagram on which pins the cables, resistor and diode need to be wired to?

**Comment by kratz00** [comment]
![hobbywing-telemetry-adapter-for-flysky-i-bus-v0-484wukb8ezvc1](https://github.com/user-attachments/assets/73c8866c-9aaa-4cf6-a72c-81e6ea7f5e29)
```
Diode is to prevent backpowering to ESC if board is connected to USB.
Resistor is necessary for the half duplex protocol using single line serial. 
```
[Source](https://www.reddit.com/r/rccars/comments/1ca4bfi/hobbywing_telemetry_adapter_for_flysky_ibus/)

**Comment by manuelrwong** [comment]
Perfect! Thank you!

**Comment by manuelrwong** [comment]
Perfect! Thank you!
